include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    avoid_print: true
    type_annotate_public_apis: false
    annotate_overrides: false
    avoid_setters_without_getters: false
    avoid_positional_boolean_parameters: false

analyzer:
  exclude:
    - test_driver/**
    - integration_test/**
  errors:
    missing_required_param: error
    parameter_assignments: error
    avoid_print: error